language: csharp
solution: MedallionShell.sln
install:
  - nuget restore MedallionShell.sln
  - nuget install NUnit.Console -Version 3.10.0 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release MedallionShell.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.10.0/tools/nunit3-console.exe ./MedallionShell.Tests/bin/Release/MyProject.Tests.dll
