version: 1.0.{build}

image: 
  - Visual Studio 2022
  - Ubuntu2204

build_script:
  # on linux, it seems like msbuild goes parallel such that if we don't build ProcessSignaler first, we won't have the net45 binary
  # to pack into the non-net45 builds
  - dotnet build MedallionShell.ProcessSignaler/MedallionShell.ProcessSignaler.csproj -c Release
  - dotnet build MedallionShell.sln -c Release

for: 
  - 
    matrix: 
      only: 
        - 
          image: "Visual Studio 2022"
    test_script:
      - dotnet test MedallionShell.sln -c Release --no-build
  - 
    matrix: 
      only: 
        - 
          image: "Ubuntu2204"
    test_script:
      # Do not test against .NET Framework on Ubuntu
      - dotnet test MedallionShell.sln -c Release -f net6.0 --no-build
      - dotnet test MedallionShell.sln -c Release -f net8.0 --no-build
