version: 1.0.{build}

image: 
  # - Visual Studio 2022
  - Ubuntu2204

environment:
  nodejs_version: "20"

before_build:
  # - which pwsh  # /usr/bin/pwsh
  # - which git # /usr/bin/git
  # - which docker # /usr/bin/docker
  # - which dotnet # /usr/bin/dotnet
  # - which node # /home/appveyor/.nvm/versions/node/v16.20.2/bin/node
  # - which go # /home/appveyor/.gvm/gos/go1.22.0/bin/go
  # - which clang # /usr/bin/clang
  # - which gcc # /usr/bin/gcc
  # - which ruby # /home/appveyor/.rbenv/shims/ruby
  # - which python3 # /usr/bin/python3
  # - which pip3 # /usr/local/bin/pip3
  # - which yarn # /usr/bin/yarn
  # - which wget # /usr/bin/wget
  # - which curl # /usr/bin/curl
  # - which cmake # /usr/bin/cmake
  # - which mysql # /usr/bin/mysql
  # - which firefox # /usr/bin/firefox
  # - pwsh --version # PowerShell 7.4.1
  # - git --version # git version 2.43.2
  # - docker --version # Docker version 25.0.3, build 4debf41
  # - dotnet --version # 8.0.200
  # - node --version # v16.20.2
  # - go version # go version go1.22.0 linux/amd64
  # - clang --version 
  # Ubuntu clang version 13.0.1-2ubuntu2.2
  # Target: x86_64-pc-linux-gnu
  # Thread model: posix
  # InstalledDir: /usr/bin
  # - gcc --version
  # gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
  # Copyright (C) 2021 Free Software Foundation, Inc.
  # This is free software; see the source for copying conditions.  There is NO
  # warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
  # - ruby --version
  #   rbenv: ruby: command not found
  # The `ruby' command exists in these Ruby versions:
  #   2.6.10
  #   2.7.8
  #   3.0.6
  #   3.1.4
  #   3.2.3
  - python3 --version
  - pip3 --version
  - yarn --version
  - wget --version
  - curl --version
  - cmake --version
  - mysql --version
  - firefox --version
  - exit 1

build_script:
  # on linux, it seems like msbuild goes parallel such that if we don't build ProcessSignaler first, we won't have the net45 binary
  # to pack into the non-net45 builds
  - dotnet build MedallionShell.ProcessSignaler/MedallionShell.ProcessSignaler.csproj -c Release
  - dotnet build MedallionShell.sln -c Release

for: 
  - 
    matrix: 
      only: 
        - 
          image: "Visual Studio 2022"
    test_script:
      # Unconditionally collect test rest afterwards
      - dotnet test MedallionShell.sln -c Release --no-build --logger:"nunit;LogFilePath=TestResult.xml" & appveyor PushArtifact TestResult.xml

  - 
    matrix: 
      only: 
        - 
          image: Ubuntu2204
    test_script:
      # Unconditionally collect test rest afterwards
      - echo DOTNET TEST
      - dotnet test MedallionShell.sln -c Release -f net6.0 --no-build --logger:"nunit;LogFilePath=TestResult.net6.0.xml"; appveyor PushArtifact TestResult.net6.0.xml
      - dotnet test MedallionShell.sln -c Release -f net8.0 --no-build --logger:"nunit;LogFilePath=TestResult.net8.0.xml"; appveyor PushArtifact TestResult.net8.0.xml
      # test mono via the NUnit console runner
      - nuget install NUnit.Console -Version 3.17.0 -OutputDirectory testrunner -Source https://api.nuget.org/v3/index.json
      - echo MONO NETCORE
      - mono ./testrunner/NUnit.ConsoleRunner.3.17.0/tools/nunit3-console.exe ./MedallionShell.Tests/bin/Release/net6.0/MedallionShell.Tests.dll
      - mono ./testrunner/NUnit.ConsoleRunner.3.17.0/tools/nunit3-console.exe ./MedallionShell.Tests/bin/Release/net8.0/MedallionShell.Tests.dll
      - echo MONO NETFRAMEWORK
      - mono ./testrunner/NUnit.ConsoleRunner.3.17.0/tools/nunit3-console.exe ./MedallionShell.Tests/bin/Release/net462/MedallionShell.Tests.dll