version: 1.0.{build}
image: Visual Studio 2019
build_script:
# see comment in .travis.yml for why we need to build ProcessSignaler explicitly
- cmd: >-
    nuget restore


    msbuild /p:Configuration=Release MedallionShell.ProcessSignaler\MedallionShell.ProcessSignaler.csproj


    msbuild /p:Configuration=Release MedallionShell.sln