version: 1.0.{build}

image: 
  - Visual Studio 2022
  - Ubuntu2204

build_script:
  # on linux, it seems like msbuild goes parallel such that if we don't build ProcessSignaler first, we won't have the net45 binary
  # to pack into the non-net45 builds
  - dotnet build MedallionShell.ProcessSignaler/MedallionShell.ProcessSignaler.csproj -c Release
  - dotnet build MedallionShell.sln -c Release

for: 
  - 
    matrix: 
      only: 
        - 
          image: "Visual Studio 2022"
    test_script:
      - dotnet test MedallionShell.sln -c Release --no-build --logger:"nunit;LogFilePath=TestResult.{framework}.xml"
  - 
    matrix: 
      only: 
        - 
          image: Ubuntu2204
    before_test:
      # https://www.appveyor.com/docs/windows-images-software/#mono
      # https://www.mono-project.com/download/stable/#download-lin
      - sudo apt install ca-certificates gnupg -qq
      - sudo gpg --homedir /tmp --no-default-keyring --keyring /usr/share/keyrings/mono-official-archive-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
      - echo "deb [signed-by=/usr/share/keyrings/mono-official-archive-keyring.gpg] https://download.mono-project.com/repo/ubuntu stable-focal main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
      - sudo apt update -qq
      - sudo apt install mono-devel -qq
    test_script:
      - echo DOTNET TEST
      # Error message for net6.0: The active test run was aborted. Reason: Test host process crashed
      - dotnet test MedallionShell.sln -c Release -f net6.0 --no-build --logger:"nunit;LogFilePath=TestResult.{framework}.xml"
      - dotnet test MedallionShell.sln -c Release -f net8.0 --no-build --logger:"nunit;LogFilePath=TestResult.{framework}.xml"
      # test mono via the NUnit console runner
      - nuget install NUnit.Console -Version 3.16.3 -OutputDirectory testrunner -Source https://api.nuget.org/v3/index.json -Verbosity quiet
      # - nuget install NUnit.Console -Version 3.17.0 -OutputDirectory testrunner -Source https://api.nuget.org/v3/index.json -Verbosity quiet
      - ls ./testrunner/NUnit.ConsoleRunner.3.16.3/tools
      - |
        echo '{
          "runtimeOptions": {
            "tfm": "net8.0",
            "frameworks": [
              {
                "name": "Microsoft.NETCore.App",
                "version": "8.0.0"
              }
            ],
            "configProperties": {
              "System.Reflection.NullabilityInfoContext.IsSupported": true
            }
          }
        }' > ./testrunner/NUnit.ConsoleRunner.3.16.3/tools/nunit3-console.runtimeconfig.json
      - echo MONO NETFRAMEWORK
      - mono ./testrunner/NUnit.ConsoleRunner.3.16.3/tools/nunit3-console.exe ./MedallionShell.Tests/bin/Release/net462/MedallionShell.Tests.dll --where "method!=TestPipeline&method!=TestProcessIOIsCancellable"
      - echo MONO NETCORE
      - mono ./testrunner/NUnit.ConsoleRunner.3.16.3/tools/nunit3-console.exe ./MedallionShell.Tests/bin/Release/net6.0/MedallionShell.Tests.dll
      - mono ./testrunner/NUnit.ConsoleRunner.3.16.3/tools/nunit3-console.exe ./MedallionShell.Tests/bin/Release/net8.0/MedallionShell.Tests.dll
