version: 1.0.{build}

image: 
  # - Visual Studio 2022
  - Ubuntu2204

environment:
  nodejs_version: "20"

before_build:
  # - which pwsh  # /usr/bin/pwsh
  # - which git # /usr/bin/git
  # - which docker # /usr/bin/docker
  # - which dotnet # /usr/bin/dotnet
  - which node
  - which go
  - which clang
  - which gcc
  - which ruby
  - which python3
  - which pip3
  - which yarn
  - which wget
  - which curl
  - which cmake
  - which mysql
  - which firefox
  - pwsh --version
  - git --version
  - docker --version
  - dotnet --version
  - node --version
  - go version
  - clang --version
  - gcc --version
  - ruby --version
  - python3 --version
  - pip3 --version
  - yarn --version
  - wget --version
  - curl --version
  - cmake --version
  - mysql --version
  - firefox --version
  - exit 1

build_script:
  # on linux, it seems like msbuild goes parallel such that if we don't build ProcessSignaler first, we won't have the net45 binary
  # to pack into the non-net45 builds
  - dotnet build MedallionShell.ProcessSignaler/MedallionShell.ProcessSignaler.csproj -c Release
  - dotnet build MedallionShell.sln -c Release

for: 
  - 
    matrix: 
      only: 
        - 
          image: "Visual Studio 2022"
    test_script:
      # Unconditionally collect test rest afterwards
      - dotnet test MedallionShell.sln -c Release --no-build --logger:"nunit;LogFilePath=TestResult.xml" & appveyor PushArtifact TestResult.xml

  - 
    matrix: 
      only: 
        - 
          image: Ubuntu2204
    test_script:
      # Unconditionally collect test rest afterwards
      - echo DOTNET TEST
      - dotnet test MedallionShell.sln -c Release -f net6.0 --no-build --logger:"nunit;LogFilePath=TestResult.net6.0.xml"; appveyor PushArtifact TestResult.net6.0.xml
      - dotnet test MedallionShell.sln -c Release -f net8.0 --no-build --logger:"nunit;LogFilePath=TestResult.net8.0.xml"; appveyor PushArtifact TestResult.net8.0.xml
      # test mono via the NUnit console runner
      - nuget install NUnit.Console -Version 3.17.0 -OutputDirectory testrunner -Source https://api.nuget.org/v3/index.json
      - echo MONO NETCORE
      - mono ./testrunner/NUnit.ConsoleRunner.3.17.0/tools/nunit3-console.exe ./MedallionShell.Tests/bin/Release/net6.0/MedallionShell.Tests.dll
      - mono ./testrunner/NUnit.ConsoleRunner.3.17.0/tools/nunit3-console.exe ./MedallionShell.Tests/bin/Release/net8.0/MedallionShell.Tests.dll
      - echo MONO NETFRAMEWORK
      - mono ./testrunner/NUnit.ConsoleRunner.3.17.0/tools/nunit3-console.exe ./MedallionShell.Tests/bin/Release/net462/MedallionShell.Tests.dll